"use client";
import {useMemo,useState} from "react";
import {ExternalLink,FileWarning,Globe2,MonitorPlay,RotateCcw,ShieldCheck} from "lucide-react";
import {PrewiseShell} from "@/components/PrewiseUI";
import {getApiClient} from "@/lib/api";
import type {BrowserSandboxResult,ExeSandboxResult} from "@/lib/types";

type View="lab"|"sandbox";
const REMOTE_URL=process.env.NEXT_PUBLIC_SANDBOX_REMOTE_URL||"";
export default function SandboxPage(){
 const [view,setView]=useState<View>("lab"),[url,setUrl]=useState("https://example.com"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [web,setWeb]=useState<BrowserSandboxResult|null>(null),[exe,setExe]=useState<ExeSandboxResult|null>(null),[sessionKey,setSessionKey]=useState(1);
 const remoteUrl=useMemo(()=>REMOTE_URL?`${REMOTE_URL}${REMOTE_URL.includes("?")?"&":"?"}autoconnect=1&resize=scale&session=${sessionKey}`:"",[sessionKey]);
 async function scanUrl(){setBusy(true);setError("");setWeb(null);try{setWeb(await getApiClient().browserSandboxUrl(url))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function scanExe(file?:File){if(!file)return;setBusy(true);setError("");setExe(null);try{setExe(await getApiClient().sandboxExecutable(file))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function reset(){setWeb(null);setExe(null);setError("");setUrl("https://example.com");setSessionKey(v=>v+1)}
 const verdict=exe?.verdict==="dangerous"?"NGUY HIỂM":exe?.verdict==="suspicious"?"ĐÁNG NGỜ":exe?.verdict==="no_obvious_theft_detected"?"CHƯA THẤY HÀNH VI ĐÁNH CẮP":"CHƯA XÁC ĐỊNH";
 return <PrewiseShell><main id="main-content" className="sandbox-page"><header className="sandbox-toolbar"><div><span>ISOLATED ENVIRONMENT</span><b>{view==="lab"?"Lab phân tích tự động":"Máy ảo tương tác"}</b></div><div className="sandbox-status"><i/>Phiên cô lập</div><button onClick={reset}><RotateCcw/>Đặt lại phiên</button></header>
 <nav className="sandbox-subtabs" aria-label="Chế độ kiểm thử"><button className={view==="lab"?"active":""} onClick={()=>setView("lab")}><ShieldCheck/>1. Lab<small>Tự động kiểm tra và báo cáo</small></button><button className={view==="sandbox"?"active":""} onClick={()=>setView("sandbox")}><MonitorPlay/>2. Sandbox<small>Dùng máy ảo trực tiếp trên web</small></button></nav>
 {view==="lab"?<><section className="live-sandbox-grid"><article className="live-sandbox-card"><Globe2/><h2>Mở website thật</h2><p>Chromium headless truy cập trang, chạy JavaScript, điền dữ liệu mồi và chặn việc gửi chúng ra ngoài.</p><form onSubmit={e=>{e.preventDefault();void scanUrl()}}><input value={url} onChange={e=>setUrl(e.target.value)} aria-label="URL cần kiểm thử"/><button disabled={busy}>Mở và kiểm thử</button></form>{web&&<div className="sandbox-report"><strong>{web.canary.exfiltration_blocked?"PHÁT HIỆN Ý ĐỊNH LẤY DỮ LIỆU":"ĐÃ CHẠY XONG"}</strong><p>{web.page_title||web.final_url} · HTTP {web.status_code??"?"}</p><ul>{web.issues.map(x=><li key={x.code}>[{x.severity}] {x.message} {x.detail}</li>)}</ul></div>}</article><article className="live-sandbox-card"><FileWarning/><h2>Chạy file EXE tự động</h2><p>Tệp được chạy trong Windows Sandbox dùng một lần và được thu thập hành vi tự động.</p><label className="exe-picker"><input type="file" accept=".exe" disabled={busy} onChange={e=>void scanExe(e.target.files?.[0])}/>{busy?"Đang kiểm thử…":"Chọn EXE để phân tích"}</label>{exe&&<div className="sandbox-report"><strong>{verdict} · {exe.risk_score}/100</strong><p><code>{exe.sha256}</code></p><ul>{exe.issues.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}</article></section>{error&&<div className="sandbox-global-error">{error}</div>}</>:
 <section className="interactive-sandbox"><header><div><MonitorPlay/><span><b>PREWISE DISPOSABLE DESKTOP</b><small>Chuột và bàn phím được chuyển vào máy ảo; phiên bị hủy khi kết thúc.</small></span></div>{remoteUrl&&<a href={remoteUrl} target="_blank" rel="noopener noreferrer"><ExternalLink/>Mở toàn màn hình</a>}</header>{remoteUrl?<iframe key={sessionKey} src={remoteUrl} title="Máy ảo sandbox tương tác" allow="clipboard-read; clipboard-write; fullscreen" referrerPolicy="no-referrer"/>:<div className="sandbox-unavailable"><MonitorPlay/><h2>Remote Desktop Gateway chưa được cấu hình</h2><p>Giao diện Sandbox đã sẵn sàng để kết nối noVNC/Apache Guacamole. Đặt biến môi trường công khai bên dưới tới gateway máy ảo dùng một lần rồi khởi động lại frontend.</p><code>NEXT_PUBLIC_SANDBOX_REMOTE_URL=https://sandbox.example.com/vnc.html</code><p>Gateway phải tự cấp một Windows VM riêng cho mỗi phiên; upload và chạy EXE sẽ diễn ra hoàn toàn bên trong desktop này.</p></div>}</section>}
 <aside className="sandbox-truth"><ShieldCheck/><div><b>Hai chế độ tách biệt</b><p><b>Lab</b> tự chạy và đánh giá. <b>Sandbox</b> truyền màn hình máy ảo để người dùng tự mở website, tải tệp và chạy EXE như trên máy thật.</p></div></aside></main></PrewiseShell>
}