from datetime import timedelta

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from backend.db import Base
from backend.models import ThreatFeedIndicator, ThreatFeedSyncState
from backend.security_utils import utcnow
from backend.services import threat_feed_service
from backend.services.threat_feed_service import (
    FeedRecord,
    _upsert_records,
    collect_local_threat_feed_evidence,
    import_phishing_database,
    parse_openphish,
    parse_phishing_database_repository,
    parse_phishtank,
    parse_urlhaus,
)
from security.risk_core import PolicyEngineV2, assess, default_config
from security.risk_core.url_overrides import URL_OVERRIDE_RULES


def _session_factory():
    engine = create_engine("sqlite+pysqlite:///:memory:")
    Base.metadata.create_all(engine)
    return sessionmaker(bind=engine)


def test_feed_parsers_accept_official_shapes():
    phishtank = (
        b"phish_id,url,submission_time,verified,online,target\n"
        b"42,https://phish.example/login,2026-01-02T03:04:05+00:00,yes,yes,Example\n"
    )
    openphish = b"https://one.example/login\nhttps://two.example/verify\n"
    urlhaus = (
        b"# generated by URLhaus\n"
        b"# id,dateadded,url,url_status,last_online,threat,tags,urlhaus_link,reporter\n"
        b"7,2026-01-02T03:04:05+00:00,http://malware.example/a,online,,malware_download,exe,,tester\n"
    )

    assert parse_phishtank(phishtank, 10)[0].source_ref == "42"
    assert len(parse_openphish(openphish, 10)) == 2
    assert parse_urlhaus(urlhaus, 10)[0].metadata["threat"] == "malware_download"


def test_local_feed_exact_match_is_high_confidence(monkeypatch):
    factory = _session_factory()
    monkeypatch.setattr(threat_feed_service, "SessionLocal", factory)
    url = "https://credential-theft.example/login"
    with factory() as db:
        assert _upsert_records(db, "openphish", [FeedRecord(url=url, tags=("phishing",))]) == 1

    evidence = collect_local_threat_feed_evidence(url)

    assert evidence[0].finding_type == "local_feed_exact_url"
    assert evidence[0].severity == 0.99
    assert evidence[0].metadata["local_lookup"] is True
    risk = assess(evidence, config=default_config(), override_rules=URL_OVERRIDE_RULES)
    policy = PolicyEngineV2().decide(risk)
    assert risk.risk_score == 90.0
    assert risk.effective_override is not None
    assert risk.effective_override.rule_id == "url-local-active-threat-feed-v1"
    assert policy.decision.value == "hard_block"


def test_expired_indicator_is_not_returned(monkeypatch):
    factory = _session_factory()
    monkeypatch.setattr(threat_feed_service, "SessionLocal", factory)
    url = "https://expired.example/login"
    with factory() as db:
        _upsert_records(db, "phishtank", [FeedRecord(url=url)])
        row = db.query(ThreatFeedIndicator).one()
        row.expires_at = utcnow() - timedelta(seconds=1)
        db.commit()

    assert collect_local_threat_feed_evidence(url) == []


def test_phishing_database_manifest_import_is_idempotent(tmp_path, monkeypatch):
    factory = _session_factory()
    monkeypatch.setattr(threat_feed_service, "SessionLocal", factory)
    active = tmp_path / "phishing-links-ACTIVE"
    active.mkdir()
    (active / "phishing-links-ACTIVE.manifest.txt").write_text(
        "active1.txt\nactive1.txt\n", encoding="utf-8"
    )
    (active / "active1.txt").write_text(
        "# generated feed\n"
        "https://phish.example/login\n"
        "https://phish.example/login\n"
        "ftp://unsupported.example/file\n",
        encoding="utf-8",
    )

    parsed = parse_phishing_database_repository(tmp_path, 10)
    first = import_phishing_database(tmp_path, limit=10)
    second = import_phishing_database(tmp_path, limit=10)

    assert len(parsed) == 1
    assert first.records_seen == 1
    assert second.records_seen == 1
    with factory() as db:
        assert db.query(ThreatFeedIndicator).count() == 1
        state = db.get(ThreatFeedSyncState, "phishing_database")
        assert state is not None
        assert state.status == "completed"


def test_local_feed_does_not_broaden_match_to_entire_domain(monkeypatch):
    factory = _session_factory()
    monkeypatch.setattr(threat_feed_service, "SessionLocal", factory)
    with factory() as db:
        _upsert_records(
            db,
            "phishing_database",
            [FeedRecord(url="https://shared.example/phishing/login")],
        )

    assert collect_local_threat_feed_evidence("https://shared.example/benign") == []
