// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/account/api-key" | "/account/billing" | "/account/checkout" | "/account/history" | "/account/mcp-connect" | "/admin" | "/analyze" | "/armor-console" | "/auth" | "/chat" | "/demo" | "/downloads" | "/history" | "/methodology" | "/pricing" | "/result/[id]" | "/result/[id]/ai-analysis" | "/sandbox" | "/settings"
type AppRouteHandlerRoutes = "/api/admin/models/train" | "/api/admin/models/train/status" | "/api/admin/settings/ai-context-weight" | "/api/admin/settings/operations" | "/api/admin/settings/url-assessment-cache" | "/api/admin/specs" | "/api/admin/specs/[specId]/status" | "/api/admin/specs/execute" | "/api/demo/chat/message" | "/api/demo/deepfake/analyze" | "/api/demo/training-data/inspect" | "/api/demo/url/analyze" | "/brand-logo"
type PageRoutes = never
type LayoutRoutes = "/" | "/account"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/account/api-key": {}
  "/account/billing": {}
  "/account/checkout": {}
  "/account/history": {}
  "/account/mcp-connect": {}
  "/admin": {}
  "/analyze": {}
  "/api/admin/models/train": {}
  "/api/admin/models/train/status": {}
  "/api/admin/settings/ai-context-weight": {}
  "/api/admin/settings/operations": {}
  "/api/admin/settings/url-assessment-cache": {}
  "/api/admin/specs": {}
  "/api/admin/specs/[specId]/status": { "specId": string; }
  "/api/admin/specs/execute": {}
  "/api/demo/chat/message": {}
  "/api/demo/deepfake/analyze": {}
  "/api/demo/training-data/inspect": {}
  "/api/demo/url/analyze": {}
  "/armor-console": {}
  "/auth": {}
  "/brand-logo": {}
  "/chat": {}
  "/demo": {}
  "/downloads": {}
  "/history": {}
  "/methodology": {}
  "/pricing": {}
  "/result/[id]": { "id": string; }
  "/result/[id]/ai-analysis": { "id": string; }
  "/sandbox": {}
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/account": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
