import { assessUrl, assessText, assessAction } from "./shared/api.js";
import { getRiskLevel, toDisplayScore } from "./shared/risk.js";
const tabResults=new Map(),urlCache=new Map(),inFlight=new Map();const CACHE_TTL=5*60*1000;let requestSequence=0;
async function settings(){const s=await chrome.storage.local.get({protectionEnabled:false,linkProtection:true,gmailProtection:true});return s}
const errorInfo=(e)=>({type:e?.type||"unknown",message:e?.message||"Đã xảy ra lỗi không xác định.",status:e?.status??null});
function setBadge(tabId,entry){if(tabId==null)return;if(entry?.status==="loading"){chrome.action.setBadgeText({tabId,text:"…"});chrome.action.setBadgeBackgroundColor({tabId,color:"#2563eb"});chrome.action.setTitle({tabId,title:"AI Security Armor — Đang kiểm tra"});return}if(entry?.error){const limited=entry.error.type==="http"&&entry.error.status===429;chrome.action.setBadgeText({tabId,text:limited?"WAIT":"?"});chrome.action.setBadgeBackgroundColor({tabId,color:limited?"#d97706":"#64748b"});chrome.action.setTitle({tabId,title:limited?"AI Security Armor — Tạm giới hạn lượt quét":"AI Security Armor — Không thể kiểm tra"});return}const level=getRiskLevel(entry?.score||0);chrome.action.setBadgeText({tabId,text:{safe:"OK",warn:"!",danger:"X"}[level.key]});chrome.action.setBadgeBackgroundColor({tabId,color:level.color});chrome.action.setTitle({tabId,title:`AI Security Armor — ${level.label} (${entry.score}/100)`})}
function cached(url){const hit=urlCache.get(url);if(hit&&Date.now()-hit.completedAt<CACHE_TTL)return hit;if(hit)urlCache.delete(url);return null}
async function handleAssessUrl(url,tabId,force=false){if(!(await settings()).protectionEnabled)return {disabled:true};if(!/^https?:\/\//i.test(url||""))return {unsupported:true};if(!force){const hit=cached(url);if(hit){if(tabId!=null){tabResults.set(tabId,hit);setBadge(tabId,hit)}return hit}if(inFlight.has(url))return inFlight.get(url)}
 const requestId=++requestSequence,startedAt=Date.now(),loading={status:"loading",url,requestId,startedAt};if(tabId!=null){tabResults.set(tabId,loading);setBadge(tabId,loading)}
 const promise=(async()=>{try{const result=await assessUrl(url);const entry={status:"complete",url,score:toDisplayScore(result.risk_score),result,requestId,startedAt,completedAt:Date.now(),latencyMs:Date.now()-startedAt};urlCache.set(url,entry);if(tabId!=null&&tabResults.get(tabId)?.requestId===requestId){tabResults.set(tabId,entry);setBadge(tabId,entry)}return entry}catch(e){const entry={status:"error",url,error:errorInfo(e),requestId,startedAt,completedAt:Date.now(),latencyMs:Date.now()-startedAt};if(tabId!=null&&tabResults.get(tabId)?.requestId===requestId){tabResults.set(tabId,entry);setBadge(tabId,entry)}return entry}finally{inFlight.delete(url)}})();inFlight.set(url,promise);return promise}
chrome.runtime.onInstalled.addListener(async()=>{const s=await chrome.storage.local.get(["protectionEnabled","linkProtection","gmailProtection"]);await chrome.storage.local.set({protectionEnabled:typeof s.protectionEnabled==="boolean"?s.protectionEnabled:false,linkProtection:typeof s.linkProtection==="boolean"?s.linkProtection:true,gmailProtection:typeof s.gmailProtection==="boolean"?s.gmailProtection:true})});
chrome.runtime.onMessage.addListener((msg,sender,sendResponse)=>{const tabId=sender.tab?.id??msg.tabId;(async()=>{try{switch(msg.type){case"ASSESS_URL":return sendResponse(await handleAssessUrl(msg.url,tabId,msg.force));case"GET_PROTECTION_STATE":return sendResponse(await settings());case"SET_PROTECTION_STATE":{await chrome.storage.local.set({protectionEnabled:msg.enabled===true});if(!msg.enabled){tabResults.clear();urlCache.clear();const tabs=await chrome.tabs.query({});await Promise.all(tabs.filter(t=>t.id!=null).map(t=>chrome.action.setBadgeText({tabId:t.id,text:""})));}else{const tabs=await chrome.tabs.query({});tabs.filter(t=>t.id!=null&&/^https?:/.test(t.url||"")).forEach(t=>handleAssessUrl(t.url,t.id));}return sendResponse({enabled:msg.enabled===true})}case"ASSESS_TEXT":{const s=await settings();if(!s.protectionEnabled||!s.gmailProtection)return sendResponse({disabled:true});try{return sendResponse({result:await assessText(msg.text,msg.modality||"email",msg.metadata),offline:false})}catch(e){return sendResponse({error:errorInfo(e)})}}case"ASSESS_ACTION":try{return sendResponse({result:await assessAction(msg.actionType,msg.targetUrl,msg.dataTypes)})}catch(e){return sendResponse({error:errorInfo(e)})}case"GET_TAB_RESULT":{const entry=tabResults.get(msg.tabId);return sendResponse(entry?.url===msg.url?entry:null)}case"GET_SETTINGS":return sendResponse(await settings());default:return sendResponse({error:{type:"unknown_message",message:"Thông điệp không được hỗ trợ."}})}}catch(e){sendResponse({error:errorInfo(e)})}})();return true});
chrome.tabs.onUpdated.addListener((tabId,info,tab)=>{if(info.status==="loading")tabResults.delete(tabId);if(info.status==="complete"&&/^https?:/.test(tab.url||""))settings().then(s=>s.protectionEnabled&&handleAssessUrl(tab.url,tabId))});chrome.tabs.onRemoved.addListener(id=>tabResults.delete(id));
