"use client";
import {useEffect,useState} from "react";
import {ExternalLink,FileWarning,Globe2,MonitorPlay,RotateCcw,ShieldCheck} from "lucide-react";
import {PrewiseShell} from "@/components/PrewiseUI";
import {getApiClient} from "@/lib/api";
import {readStoredAccessToken} from "@/lib/auth-session";
import type {BrowserSandboxResult,ExeSandboxResult} from "@/lib/types";

type View="lab"|"sandbox"; type Tier="free"|"pro"|"max";
type CloudSession={id:string;tier:Tier;status:string;remoteUrl:string|null;expiresAt:string;error:string|null};
type FreeBrowser={url:string;title:string;image:string;width:number;height:number};
type CloudStatus={accountTier:Tier;credits:number;availableTiers:Array<{tier:Tier;web:boolean;exe:boolean;gpu:boolean;minutes:number;provider:string;allowed:boolean}>;cloudConfigured:boolean;freeConfigured:boolean;session:CloudSession|null};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:8000").replace(/\/$/,"");
async function cloudRequest<T>(path:string,init?:RequestInit):Promise<T>{const token=readStoredAccessToken();const response=await fetch(`${API}/v1/sandbox-cloud${path}`,{...init,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.detail||`Lỗi ${response.status}`);return response.json()}
export default function SandboxPage(){
 const [view,setView]=useState<View>("lab"),[url,setUrl]=useState("https://example.com"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [web,setWeb]=useState<BrowserSandboxResult|null>(null),[exe,setExe]=useState<ExeSandboxResult|null>(null),[cloud,setCloud]=useState<CloudStatus|null>(null),[selected,setSelected]=useState<Tier>("free"),[freeBrowser,setFreeBrowser]=useState<FreeBrowser|null>(null),[freeUrl,setFreeUrl]=useState("https://example.com");
 async function refresh(){try{const value=await cloudRequest<CloudStatus>("/status");setCloud(value);if(value.session)setSelected(value.session.tier)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{if(view==="sandbox")void refresh()},[view]);
 useEffect(()=>{if(!cloud?.session||!["provisioning"].includes(cloud.session.status))return;const timer=setInterval(()=>void refresh(),3000);return()=>clearInterval(timer)},[cloud?.session?.status]);
 async function startSession(){setBusy(true);setError("");try{const created=await cloudRequest<CloudSession>("/sessions",{method:"POST",body:JSON.stringify({tier:selected})});await refresh();if(created.tier==="free")setFreeBrowser(await cloudRequest<FreeBrowser>(`/sessions/${created.id}/browser`))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function freeAction(path:string,body:object){if(!session)return;setBusy(true);try{setFreeBrowser(await cloudRequest<FreeBrowser>(`/sessions/${session.id}/browser/${path}`,{method:"POST",body:JSON.stringify(body)}))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function stopSession(){if(!cloud?.session)return;setBusy(true);try{await cloudRequest(`/sessions/${cloud.session.id}`,{method:"DELETE"});await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function scanUrl(){setBusy(true);setError("");try{setWeb(await getApiClient().browserSandboxUrl(url))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function scanExe(file?:File){if(!file)return;setBusy(true);setError("");try{setExe(await getApiClient().sandboxExecutable(file))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const session=cloud?.session,remoteUrl=session?.status==="ready"?session.remoteUrl:null;
 useEffect(()=>{if(session?.tier==="free"&&session.status==="ready"&&!freeBrowser)cloudRequest<FreeBrowser>(`/sessions/${session.id}/browser`).then(setFreeBrowser).catch(()=>{})},[session?.id,session?.status]);
 return <PrewiseShell><main id="main-content" className="sandbox-page"><header className="sandbox-toolbar"><div><span>ISOLATED ENVIRONMENT</span><b>{view==="lab"?"Lab phân tích tự động":"Máy ảo theo gói tài khoản"}</b></div><div className="sandbox-status"><i/>{cloud?`${cloud.accountTier.toUpperCase()} · ${cloud.credits} lượt`:`Phiên cô lập`}</div><button onClick={()=>{setWeb(null);setExe(null);setError("");void refresh()}}><RotateCcw/>Làm mới</button></header>
 <nav className="sandbox-subtabs"><button className={view==="lab"?"active":""} onClick={()=>setView("lab")}><ShieldCheck/>1. Lab<small>Tự động kiểm tra</small></button><button className={view==="sandbox"?"active":""} onClick={()=>setView("sandbox")}><MonitorPlay/>2. Sandbox<small>Desktop tương tác</small></button></nav>
 {view==="lab"?<section className="live-sandbox-grid"><article className="live-sandbox-card"><Globe2/><h2>Mở website thật</h2><form onSubmit={e=>{e.preventDefault();void scanUrl()}}><input value={url} onChange={e=>setUrl(e.target.value)}/><button disabled={busy}>Kiểm thử</button></form>{web&&<div className="sandbox-report"><strong>{web.canary.exfiltration_blocked?"PHÁT HIỆN RÒ RỈ":"HOÀN TẤT"}</strong><p>{web.page_title||web.final_url}</p></div>}</article><article className="live-sandbox-card"><FileWarning/><h2>Phân tích EXE</h2><label className="exe-picker"><input type="file" accept=".exe" disabled={busy} onChange={e=>void scanExe(e.target.files?.[0])}/>Chọn EXE</label>{exe&&<div className="sandbox-report"><strong>{exe.verdict} · {exe.risk_score}/100</strong></div>}</article></section>:<>
 {!session&&<section className="sandbox-tier-grid">{cloud?.availableTiers.map(item=><button key={item.tier} disabled={!item.allowed} className={`${selected===item.tier?"selected":""} ${!item.allowed?"locked":""}`} onClick={()=>setSelected(item.tier)}><b>{item.tier.toUpperCase()}</b><strong>{item.tier==="free"?"Web cơ bản":item.tier==="pro"?"EXE chuyên dụng":"Game / GPU"}</strong><span>{item.minutes} phút · {item.provider==="local"?"Local":"Cloud"}</span><ul><li>✓ Mở website</li><li>{item.exe?"✓":"—"} Chạy EXE</li><li>{item.gpu?"✓":"—"} GPU/ứng dụng nặng</li></ul>{!item.allowed&&<em>Cần nâng gói</em>}</button>)}</section>}
 <section className="interactive-sandbox"><header><div><MonitorPlay/><span><b>{session?`${session.tier.toUpperCase()} SANDBOX`:`SANDBOX ${selected.toUpperCase()}`}</b><small>{session?.status||"Chọn môi trường phù hợp rồi bắt đầu"}</small></span></div>{remoteUrl&&<a href={remoteUrl} target="_blank" rel="noopener noreferrer"><ExternalLink/>Toàn màn hình</a>}</header>{remoteUrl?<iframe src={remoteUrl} title="Máy ảo tương tác" allow="fullscreen" referrerPolicy="no-referrer"/>:<div className="sandbox-unavailable"><MonitorPlay/><h2>{session?.status==="provisioning"?"Đang tự động cấp máy…":"Sẵn sàng tạo phiên"}</h2><p>{selected==="free"?"Môi trường local chỉ mở web, một lượt trải nghiệm mỗi ngày.":selected==="pro"?"Windows cloud dành cho EXE; dùng một credit.":"Windows GPU cloud cho game và file nặng; dùng một credit."}</p>{!session?<button disabled={busy||!cloud?.availableTiers.find(x=>x.tier===selected)?.allowed} onClick={()=>void startSession()}>Bắt đầu Sandbox {selected.toUpperCase()}</button>:<button disabled={busy} onClick={()=>void stopSession()}>Kết thúc phiên</button>}</div>}</section></>}
 {error&&<div className="sandbox-global-error">{error}</div>}</main></PrewiseShell>}
