"use client";
import Image from "next/image";
import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";
import {Suspense,useEffect,useState,type FormEvent} from "react";
import {Eye,EyeOff,LockKeyhole,Mail,UserRound} from "lucide-react";
import {useAuth} from "@/context/AuthContext";
import {getApiClient} from "@/lib/api";

const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
type Mode="login"|"register"|"forgot"|"reset";
function AuthContent(){const search=useSearchParams(),router=useRouter(),{session,isHydrated,setSession}=useAuth();const initial=(search.get("mode") as Mode)||"login",nextPath=search.get("next")?.startsWith("/")?search.get("next")!:"/analyze",[mode,setMode]=useState<Mode>(initial),[email,setEmail]=useState(""),[name,setName]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[token,setToken]=useState(search.get("token")||""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{if(isHydrated&&session!==null)router.replace(session.user.role==="admin"?"/admin":nextPath)},[isHydrated,nextPath,router,session]);
 function change(next:Mode){setMode(next);setError("");setNotice("")}
 async function submit(e:FormEvent){e.preventDefault();setError("");setNotice("");if((mode!=="reset")&&!emailPattern.test(email.trim())){setError("Vui lòng nhập địa chỉ email hợp lệ.");return}if(mode==="register"&&!name.trim()){setError("Vui lòng nhập tên hiển thị.");return}if(mode==="login"&&!password){setError("Vui lòng nhập mật khẩu.");return}if((mode==="register"||mode==="reset")&&password.length<12){setError("Mật khẩu phải có ít nhất 12 ký tự.");return}if((mode==="register"||mode==="reset")&&!/[A-Za-zÀ-ỹ]/.test(password)||((mode==="register"||mode==="reset")&&!/\d/.test(password))){setError("Mật khẩu phải chứa cả chữ và số.");return}if((mode==="register"||mode==="reset")&&password!==confirm){setError("Hai mật khẩu chưa khớp.");return}setBusy(true);try{const api=getApiClient();if(mode==="login"){const session=await api.login({email:email.trim(),password});setSession(session);router.replace(session.user.role==="admin"?"/admin":nextPath)}else if(mode==="register"){const session=await api.register({email:email.trim(),password,displayName:name.trim()});setSession(session);router.replace(nextPath)}else if(mode==="forgot"){const result=await api.requestPasswordReset(email.trim());setNotice(result.message);if(result.resetToken){setToken(result.resetToken);setMode("reset")}}else{if(!token){setError("Thiếu mã đặt lại mật khẩu.");return}await api.resetPassword(token,password);setNotice("Mật khẩu đã được cập nhật. Bạn có thể đăng nhập.");setMode("login");setPassword("");setConfirm("")}}catch(x){setError(x instanceof Error?x.message:"Không thể xử lý yêu cầu.")}finally{setBusy(false)}}
 const title=mode==="login"?"Chào mừng trở lại":mode==="register"?"Tạo tài khoản Prewise":mode==="forgot"?"Khôi phục quyền truy cập":"Đặt mật khẩu mới";const subtitle=mode==="login"?"Đăng nhập để đồng bộ lịch sử, gói và khóa tích hợp.":mode==="register"?"Tạo danh tính bảo mật của bạn trong vài bước.":mode==="forgot"?"Nhập email đã đăng ký để tạo yêu cầu đặt lại mật khẩu.":"Mật khẩu mới phải có ít nhất 12 ký tự, gồm chữ và số.";
 return <main id="main-content" className="auth-page"><Link href="/" className="auth-back">← Về trang chủ</Link><section className="auth-stage"><aside className="auth-story"><Link href="/" className="auth-logo"><Image src="/brand-logo?v=3" width={180} height={60} priority unoptimized alt="Prewise"/></Link><span>IDENTITY / TRUST LAYER</span><h1>Quyền truy cập<br/>bắt đầu từ danh tính.</h1><p>Tài khoản liên kết các lần phân tích, quyền sử dụng sandbox và thông tin tích hợp vào một lớp bảo mật duy nhất.</p><div><i/><small>KẾT NỐI ĐƯỢC MÃ HÓA · DATABASE-BACKED AUTH</small></div></aside><section className="auth-card" aria-labelledby="auth-title"><header><span>{mode.toUpperCase()} / PREWISE</span><h2 id="auth-title">{title}</h2><p>{subtitle}</p></header>{error&&<div className="auth-alert error" role="alert">{error}</div>}{notice&&<div className="auth-alert success" role="status">{notice}</div>}<form onSubmit={submit} noValidate>{mode==="register"&&<label><span>Tên hiển thị</span><div><UserRound aria-hidden/><input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" placeholder="Nguyễn Văn A"/></div></label>}{mode!=="reset"&&<label><span>Email</span><div><Mail aria-hidden/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="ban@example.com"/></div></label>}{mode==="reset"&&<label><span>Mã đặt lại</span><div><LockKeyhole aria-hidden/><input value={token} onChange={e=>setToken(e.target.value)} autoComplete="one-time-code" placeholder="Mã đặt lại mật khẩu"/></div></label>}{mode!=="forgot"&&<label><span>{mode==="reset"?"Mật khẩu mới":"Mật khẩu"}</span><div><LockKeyhole aria-hidden/><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==="login"?"current-password":"new-password"} placeholder="Tối thiểu 12 ký tự"/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?"Ẩn mật khẩu":"Hiện mật khẩu"}>{show?<EyeOff aria-hidden/>:<Eye aria-hidden/>}</button></div></label>}{(mode==="register"||mode==="reset")&&<label><span>Nhập lại mật khẩu</span><div><LockKeyhole aria-hidden/><input type={show?"text":"password"} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" placeholder="Nhập lại mật khẩu"/></div></label>}<button className="auth-submit" disabled={busy}>{busy?"Đang xử lý…":mode==="login"?"Đăng nhập →":mode==="register"?"Tạo tài khoản →":mode==="forgot"?"Tạo yêu cầu khôi phục →":"Cập nhật mật khẩu →"}</button></form>{mode==="login"&&<button className="auth-text-action" onClick={()=>change("forgot")}>Quên mật khẩu?</button>}<footer>{mode==="login"?<>Chưa có tài khoản? <button onClick={()=>change("register")}>Đăng ký</button></>:mode==="register"?<>Đã có tài khoản? <button onClick={()=>change("login")}>Đăng nhập</button></>:<>Quay lại <button onClick={()=>change("login")}>Đăng nhập</button></>}</footer></section></section></main>}
export default function AuthPage(){return <Suspense fallback={<main className="auth-page"/>}><AuthContent/></Suspense>}
