'use client';

import { useCallback, useEffect, useState } from 'react';

type Feedback = { id:string; requestId:string; feedbackType:string; reason:string; status:string; modality:string; details?:string|null; adminNote?:string|null; createdAt:string };
type Entry = { id:string; email:string; product:string; createdAt:string; unsubscribedAt?:string|null; notifiedAt?:string|null };
type Props = { authHeaders: Record<string,string> };

export function AdminFeedbackReleases({ authHeaders }: Props) {
 const [feedback,setFeedback]=useState<Feedback[]>([]),[entries,setEntries]=useState<Entry[]>([]);
 const [status,setStatus]=useState(''),[notice,setNotice]=useState(''),[notes,setNotes]=useState<Record<string,string>>({});
 const [release,setRelease]=useState({product:'browser_extension',version:'',downloadUrl:'',checksumSha256:'',signatureNote:'',notify:true});
 const [emailConfigured,setEmailConfigured]=useState(false),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setNotice('');try{const suffix=status?`?status=${status}`:'';const [f,w,r]=await Promise.all([fetch(`/api/admin/feedback${suffix}`,{headers:authHeaders,cache:'no-store'}),fetch('/api/admin/waitlist?active_only=false',{headers:authHeaders,cache:'no-store'}),fetch('/api/admin/waitlist/releases',{headers:authHeaders,cache:'no-store'})]);if(!f.ok||!w.ok||!r.ok)throw new Error('Không thể tải dữ liệu phản hồi/phát hành.');const fd=await f.json(),wd=await w.json(),rd=await r.json();setFeedback(fd.feedback||[]);setEntries(wd.entries||[]);setEmailConfigured(Boolean(rd.emailConfigured));}catch(e){setNotice(e instanceof Error?e.message:'Không thể tải dữ liệu.');}},[authHeaders,status]);
 useEffect(()=>{void load();},[load]);
 async function updateFeedback(item:Feedback,nextStatus:string){setBusy(true);try{const response=await fetch(`/api/admin/feedback/${item.id}`,{method:'PATCH',headers:{...authHeaders,'Content-Type':'application/json'},body:JSON.stringify({status:nextStatus,note:notes[item.id]??item.adminNote??null})});if(!response.ok)throw new Error('Không thể cập nhật phản hồi.');await load();setNotice('Đã cập nhật phản hồi.');}catch(e){setNotice(e instanceof Error?e.message:'Có lỗi xảy ra.');}finally{setBusy(false);}}
 async function unsubscribe(id:string){setBusy(true);const response=await fetch(`/api/admin/waitlist/${id}`,{method:'DELETE',headers:authHeaders});setBusy(false);if(response.ok){await load();setNotice('Đã hủy đăng ký.');}else setNotice('Không thể hủy đăng ký.');}
 async function exportCsv(){const response=await fetch('/api/admin/waitlist/export',{headers:authHeaders});if(!response.ok){setNotice('Không thể xuất CSV.');return;}const url=URL.createObjectURL(await response.blob()),anchor=document.createElement('a');anchor.href=url;anchor.download='prewise-waitlist.csv';anchor.click();URL.revokeObjectURL(url);}
 async function publish(){setBusy(true);setNotice('');try{const response=await fetch('/api/admin/waitlist/releases',{method:'POST',headers:{...authHeaders,'Content-Type':'application/json'},body:JSON.stringify(release)});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Không thể phát hành.');const n=data.notification;setNotice(n.configured?`Đã phát hành; gửi ${n.sent}/${n.attempted} email (${n.failed} lỗi).`:'Đã phát hành manifest. Email chưa gửi vì Cloudflare Email Sending chưa được cấu hình.');await load();}catch(e){setNotice(e instanceof Error?e.message:'Không thể phát hành.');}finally{setBusy(false);}}
 return <section className="space-y-8" aria-labelledby="feedback-release-title">
  <div><span className="text-xs font-mono text-cyan-300">04 / FEEDBACK &amp; RELEASES</span><h2 id="feedback-release-title" className="mt-2 text-3xl font-semibold">Phản hồi &amp; phát hành</h2><p className="mt-2 text-sm text-slate-400">Duyệt phản hồi, quản lý danh sách chờ và công bố bộ cài đã xác minh.</p></div>
  {notice&&<p className="rounded border border-cyan-900 bg-cyan-950/30 p-3 text-sm text-cyan-100" role="status">{notice}</p>}
  <div className="rounded-xl border border-slate-700 bg-slate-950/50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-semibold">Phản hồi người dùng</h3><select aria-label="Lọc trạng thái" value={status} onChange={e=>setStatus(e.target.value)} className="rounded border border-slate-600 bg-slate-900 p-2"><option value="">Tất cả</option>{['received','reviewing','resolved','rejected'].map(x=><option key={x}>{x}</option>)}</select></div>
   <div className="mt-4 space-y-3">{feedback.map(item=><article key={item.id} className="rounded border border-slate-800 p-4"><div className="flex flex-wrap justify-between gap-2"><b>{item.feedbackType} · {item.modality}</b><code className="text-xs text-slate-400">{item.requestId}</code></div><p className="mt-2 text-sm text-slate-300">{item.reason}: {item.details||'Không có mô tả'}</p><textarea aria-label={`Ghi chú ${item.requestId}`} className="mt-3 w-full rounded border border-slate-700 bg-slate-900 p-2 text-sm" maxLength={2000} placeholder="Ghi chú nội bộ (PII sẽ được che)…" value={notes[item.id]??item.adminNote??''} onChange={e=>setNotes({...notes,[item.id]:e.target.value})}/><div className="mt-3 flex flex-wrap gap-2">{['received','reviewing','resolved','rejected'].map(x=><button key={x} type="button" disabled={busy||item.status===x} onClick={()=>void updateFeedback(item,x)} className="rounded border border-slate-600 px-3 py-1 text-xs disabled:opacity-40">{x}</button>)}</div></article>)}{!feedback.length&&<p className="text-sm text-slate-400">Không có phản hồi phù hợp.</p>}</div>
  </div>
  <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-xl border border-slate-700 bg-slate-950/50 p-5"><div className="flex justify-between gap-3"><h3 className="text-xl font-semibold">Danh sách chờ</h3><button type="button" onClick={()=>void exportCsv()} className="rounded border border-slate-600 px-3 py-2 text-sm">Xuất CSV</button></div><div className="mt-4 space-y-2">{entries.map(entry=><div key={entry.id} className="flex items-center justify-between gap-3 border-b border-slate-800 py-2 text-sm"><span className="min-w-0 truncate"><b>{entry.email}</b><small className="block text-slate-500">{entry.product}{entry.unsubscribedAt?' · đã hủy':''}</small></span>{!entry.unsubscribedAt&&<button type="button" disabled={busy} onClick={()=>void unsubscribe(entry.id)} className="text-rose-300">Hủy</button>}</div>)}</div></div>
   <div className="rounded-xl border border-slate-700 bg-slate-950/50 p-5"><h3 className="text-xl font-semibold">Phát hành phiên bản</h3><p className={`mt-2 text-xs ${emailConfigured?'text-emerald-300':'text-amber-300'}`}>{emailConfigured?'Email Cloudflare đã cấu hình':'Chưa cấu hình email; manifest vẫn có thể phát hành nhưng sẽ không gửi mail'}</p><div className="mt-4 grid gap-3"><select value={release.product} onChange={e=>setRelease({...release,product:e.target.value})} className="rounded border border-slate-600 bg-slate-900 p-2"><option value="browser_extension">Browser extension</option></select><input placeholder="Phiên bản, ví dụ 1.0.0" value={release.version} onChange={e=>setRelease({...release,version:e.target.value})} className="rounded border border-slate-600 bg-slate-900 p-2"/><input placeholder="https://.../extension.zip" value={release.downloadUrl} onChange={e=>setRelease({...release,downloadUrl:e.target.value})} className="rounded border border-slate-600 bg-slate-900 p-2"/><input placeholder="SHA-256 (64 ký tự hex)" value={release.checksumSha256} onChange={e=>setRelease({...release,checksumSha256:e.target.value})} className="rounded border border-slate-600 bg-slate-900 p-2 font-mono text-xs"/><input placeholder="Ghi chú chữ ký số" value={release.signatureNote} onChange={e=>setRelease({...release,signatureNote:e.target.value})} className="rounded border border-slate-600 bg-slate-900 p-2"/><label className="text-sm"><input type="checkbox" checked={release.notify} onChange={e=>setRelease({...release,notify:e.target.checked})}/> <span className="ml-2">Thông báo người đang đăng ký</span></label><button type="button" disabled={busy} onClick={()=>void publish()} className="rounded bg-cyan-700 p-3 font-semibold disabled:opacity-40">{busy?'Đang xử lý…':'Phát hành'}</button></div></div>
  </div>
 </section>;
}
