"use client";
import {useEffect,useState} from "react";import {PrewiseShell} from "@/components/PrewiseUI";
type Tab="appearance"|"privacy"|"data"|"language";type Prefs={motion:string;density:string;saveHistory:boolean;maskSensitive:boolean;language:string};
const defaults:Prefs={motion:"balanced",density:"comfortable",saveHistory:true,maskSensitive:true,language:"vi"};
export default function Settings(){const [tab,setTab]=useState<Tab>("appearance"),[prefs,setPrefs]=useState<Prefs>(defaults),[notice,setNotice]=useState(""),[confirmClear,setConfirmClear]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("prewise-settings")||"null");if(saved)setPrefs({...defaults,...saved})}catch{}},[]);
 useEffect(()=>{document.documentElement.dataset.motion=prefs.motion;document.documentElement.dataset.density=prefs.density;try{localStorage.setItem("prewise-settings",JSON.stringify(prefs))}catch{}},[prefs]);
 const update=(patch:Partial<Prefs>)=>{setPrefs(v=>({...v,...patch}));setNotice("Đã lưu thay đổi");setTimeout(()=>setNotice(""),1800)};
 const clear=()=>{localStorage.removeItem("prewise-history");setConfirmClear(false);setNotice("Đã xóa toàn bộ lịch sử cục bộ");setTimeout(()=>setNotice(""),2200)};
 return <PrewiseShell><main className="inner-page settings-page"><header className="inner-head"><p className="eyebrow"><i/> PERSONAL EXPERIENCE</p><h1>Cài đặt</h1><p>Điều chỉnh Prewise theo cách bạn đọc, làm việc và bảo vệ dữ liệu.</p>{notice&&<div className="settings-notice" role="status">✓ {notice}</div>}</header><div className="settings-grid"><nav aria-label="Danh mục cài đặt">{[["appearance","Giao diện"],["privacy","Quyền riêng tư"],["data","Dữ liệu"],["language","Ngôn ngữ"]].map(x=><button className={tab===x[0]?"active":""} onClick={()=>setTab(x[0] as Tab)} key={x[0]}>{x[1]}</button>)}</nav><section>
 {tab==="appearance"&&<><div className="setting-block"><div><h2>Chuyển động</h2><p>Điều chỉnh animation và hiệu ứng không gian.</p></div><div className="option-cards">{[["full","Đầy đủ","Cinematic và phản hồi vật lý"],["balanced","Cân bằng","Mượt mà, tối ưu hiệu năng"],["reduced","Tối giản","Chỉ chuyển trạng thái thiết yếu"]].map(x=><button className={prefs.motion===x[0]?"selected":""} onClick={()=>update({motion:x[0]})} key={x[0]}><i>{prefs.motion===x[0]?"●":"○"}</i><b>{x[1]}</b><small>{x[2]}</small></button>)}</div></div><div className="setting-block"><div><h2>Mật độ giao diện</h2><p>Khoảng cách giữa các thành phần trong workspace.</p></div><div className="segments"><button className={prefs.density==="comfortable"?"active":""} onClick={()=>update({density:"comfortable"})}>Thoải mái</button><button className={prefs.density==="compact"?"active":""} onClick={()=>update({density:"compact"})}>Gọn</button></div></div></>}
 {tab==="privacy"&&<><Toggle title="Lưu lịch sử trên thiết bị" detail="Giữ tối đa 20 lần phân tích gần nhất trong trình duyệt." checked={prefs.saveHistory} onChange={v=>update({saveHistory:v})}/><Toggle title="Che dữ liệu nhạy cảm" detail="Ẩn mật khẩu, OTP và thông tin thanh toán trong bản xem trước." checked={prefs.maskSensitive} onChange={v=>update({maskSensitive:v})}/><div className="privacy-note"><b>◉ Dữ liệu thuộc quyền kiểm soát của bạn</b><p>Prewise không dùng webcam hoặc microphone. Nội dung chỉ được xử lý khi bạn chủ động nhấn Phân tích.</p></div></>}
 {tab==="data"&&<><div className="setting-block"><h2>Dữ liệu được lưu cục bộ</h2><p>Lịch sử phân tích và tùy chọn giao diện được lưu trong trình duyệt này. Chúng không tự đồng bộ sang thiết bị khác.</p></div><div className="danger-zone"><div><h2>Xóa lịch sử phân tích</h2><p>Thao tác này không thể hoàn tác.</p></div>{confirmClear?<div className="confirm-actions"><button onClick={()=>setConfirmClear(false)}>Hủy</button><button className="danger-confirm" onClick={clear}>Xác nhận xóa</button></div>:<button onClick={()=>setConfirmClear(true)}>Xóa dữ liệu</button>}</div></>}
 {tab==="language"&&<div className="setting-block"><div><h2>Ngôn ngữ giao diện</h2><p>Lựa chọn được lưu cho các phiên truy cập tiếp theo.</p></div><div className="option-cards language-options"><button className={prefs.language==="vi"?"selected":""} onClick={()=>update({language:"vi"})}><i>{prefs.language==="vi"?"●":"○"}</i><b>Tiếng Việt</b><small>Ngôn ngữ hiện tại</small></button><button className={prefs.language==="en"?"selected":""} onClick={()=>update({language:"en"})}><i>{prefs.language==="en"?"●":"○"}</i><b>English</b><small>Interface preference</small></button></div><p className="settings-help">Bản dịch tiếng Anh đầy đủ sẽ được áp dụng khi gói ngôn ngữ hoàn tất.</p></div>}
 </section></div></main></PrewiseShell>}
function Toggle({title,detail,checked,onChange}:{title:string;detail:string;checked:boolean;onChange:(v:boolean)=>void}){return <div className="setting-block switch-row"><div><h2>{title}</h2><p>{detail}</p></div><label className="switch"><input checked={checked} onChange={e=>onChange(e.target.checked)} type="checkbox"/><span/></label></div>}
