import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, ArrowRight, Ban, Box, Check, ChevronDown, CircleUserRound, Download, FileSearch, FileUp, Globe2, HardDrive, HelpCircle, LockKeyhole, Mail, MessageSquare, PackageOpen, RefreshCw, RotateCcw, Search, Send, Settings, Shield, ShieldCheck, SlidersHorizontal, Wifi } from 'lucide-react';
import { Assessment, MailItem, askContext, assessEmail, assessUrl } from './api';

type View = 'web' | 'email' | 'local' | 'settings';
const samples: MailItem[] = [
  { id:'1', sender:'Vietcombank', email:'noreply@vtcb-alert.xyz', subject:'Tài khoản của bạn sẽ bị khóa!', preview:'Xác minh ngay để tránh gián đoạn...', content:'KHẨN CẤP: Tài khoản của bạn sẽ bị khóa. Truy cập https://vietc0mbank-secure.xyz/login và nhập mật khẩu để xác minh.' },
  { id:'2', sender:'Ưu đãi thành viên', email:'offers@deal-now.co', subject:'Khuyến mãi đặc biệt chỉ hôm nay', preview:'Nhận quà trước 23:59...', content:'Ưu đãi chỉ hôm nay. Bấm bit.ly/x để nhận quà và xác nhận tài khoản.' },
  { id:'3', sender:'Nhóm dự án', email:'team@company.vn', subject:'Biên bản họp tuần', preview:'Các đầu việc đã thống nhất...', content:'Chào đội, đây là biên bản họp tuần và các đầu việc đã thống nhất. Vui lòng phản hồi trong luồng nội bộ.' },
  { id:'4', sender:'Phòng kế toán', email:'billing@company.vn', subject:'Hóa đơn tháng 6', preview:'Hóa đơn nội bộ đã phát hành...', content:'Hóa đơn tháng 6 đã được phát hành trên cổng nội bộ. Không có liên kết bên ngoài.' },
];
const riskText = (r?: Assessment) => !r ? '' : r.riskLevel === 'danger' ? 'RỦI RO CAO' : r.riskLevel === 'warn' ? 'ĐÁNG NGỜ' : 'AN TOÀN';

function App() {
  const [view,setView]=useState<View>('web'); const [url,setUrl]=useState(''); const [result,setResult]=useState<Assessment>(); const [busy,setBusy]=useState(false); const [status,setStatus]=useState('Sẵn sàng');
  const [mails,setMails]=useState(samples); const [selected,setSelected]=useState(samples[0]); const [mailBusy,setMailBusy]=useState(false); const [question,setQuestion]=useState(''); const [messages,setMessages]=useState<{role:'user'|'ai';text:string}[]>([]); const [chatOpen,setChatOpen]=useState(false);
  const context=useMemo(()=>view==='web'?url:selected.content,[view,url,selected]);
  async function scanUrl(){ if(!url.trim())return; setBusy(true);setResult(undefined); for(const s of ['Phân tích cấu trúc URL','Chạy model phân loại','Kiểm tra nội dung & prompt injection','Sinh giải thích & khuyến nghị']){setStatus(s);await new Promise(r=>setTimeout(r,260));} try{setResult(await assessUrl(url.trim()));setStatus('Đã hoàn tất');}catch(e){setStatus(e instanceof Error?e.message:'Quét thất bại');}finally{setBusy(false);} }
  async function scanMail(mail:MailItem){setSelected(mail); if(mail.result)return;setMailBusy(true);try{const r=await assessEmail(`${mail.sender} <${mail.email}>\nChủ đề: ${mail.subject}\n${mail.content}`);setMails(v=>v.map(x=>x.id===mail.id?{...x,result:r,score:r.score}:x));setSelected({...mail,result:r,score:r.score});}finally{setMailBusy(false);} }
  async function send(){if(!question.trim())return;const q=question;setQuestion('');setChatOpen(true);setMessages(v=>[...v,{role:'user',text:q}]);const answer=await askContext(q,context);setMessages(v=>[...v,{role:'ai',text:answer}]);}
  function exportReport(){const r=view==='web'?result:selected.result;if(!r)return;const text=`AI SECURITY ARMOR\nĐiểm: ${r.score}/100 — ${riskText(r)}\nĐộ tin cậy: ${Math.round(r.confidence*100)}%\n\nLý do:\n${r.reasons.map(x=>'- '+x).join('\n')}\n\n${r.explanation||''}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download=`ai-security-report-${r.requestId}.txt`;a.click();URL.revokeObjectURL(a.href);}
  return <main className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>setView('web')}><span className="brandmark"><ShieldCheck size={20}/></span><span>AI Security <b>Armor</b></span></button><nav><button className={view==='web'?'active':''} onClick={()=>setView('web')}><Globe2/>Website Check</button><button className={view==='email'?'active':''} onClick={()=>setView('email')}><Mail/>Email Guard</button><button className={view==='local'?'active':''} onClick={()=>setView('local')}><HardDrive/>Local Shield</button></nav><div className="top-actions"><span className="online"><i/>Local shield active</span><button className={view==='settings'?'icon active':'icon'} onClick={()=>setView('settings')} aria-label="Cài đặt"><Settings/></button><button className="profile"><CircleUserRound/><span>Nguyễn An</span><ChevronDown size={15}/></button></div></header>
    {view==='web'&&<section className="workspace">
      <div className="browserbar"><div className="browser-actions"><button><ArrowLeft/></button><button><ArrowRight/></button><button onClick={()=>{setResult(undefined);setStatus('Sẵn sàng')}}><RotateCcw/></button></div><div className="address"><Shield size={16}/><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==='Enter'&&scanUrl()} placeholder="Nhập URL cần kiểm tra..."/><span>Không mở trang thật</span></div><button className="scan" disabled={busy||!url.trim()} onClick={scanUrl}>{busy?<RefreshCw className="spin"/>:<Search/>}{busy?'Đang quét':'Quét URL'}</button></div>
      {!result&&!busy?<EmptyWeb setUrl={setUrl} scan={()=>setTimeout(scanUrl,0)}/>:busy?<Pipeline current={status}/>:<ResultPanel result={result!} target={url} exportReport={exportReport}/>} 
    </section>}
    {view==='email'&&<section className="workspace email"><div className="email-tools"><button><RefreshCw/>Đồng bộ</button><label className="button"><FileUp/>Nhập file .eml<input type="file" accept=".eml" hidden onChange={e=>{const f=e.target.files?.[0];if(f){const reader=new FileReader();reader.onload=()=>{const mail={id:String(Date.now()),sender:'Email đã nhập',email:f.name,subject:f.name,preview:'Tệp email cục bộ',content:String(reader.result)};setMails(v=>[mail,...v]);scanMail(mail)};reader.readAsText(f)}}}/></label><span className="spacer"/><button><SlidersHorizontal/>Tất cả</button><div className="risk-filter"><i className="danger"/><i className="warn"/><i className="safe"/></div></div><div className="mail-grid"><aside><div className="pane-title"><div><b>Hộp thư bảo vệ</b><small>{mails.length} thư đã được cô lập</small></div><ShieldCheck/></div>{mails.map(m=><button key={m.id} onClick={()=>scanMail(m)} className={selected.id===m.id?'mail-item selected':'mail-item'}><span className={`mail-score ${m.result?.riskLevel||''}`}>{m.result?m.result.score:'—'}</span><span><b>{m.sender}</b><strong>{m.subject}</strong><small>{m.preview}</small></span><time>Hôm nay</time></button>)}</aside><article className="mail-detail">{mailBusy?<Pipeline current="Đang phân tích email trong vùng cô lập" compact/>:<MailResult mail={selected} onScan={()=>scanMail(selected)} exportReport={exportReport}/>}</article></div></section>}
    {view==='local'&&<LocalShield/>}
    {view==='settings'&&<SettingsView/>}
    <div className={chatOpen?'chat-drawer open':'chat-drawer'}>{chatOpen&&<><div className="chat-head"><span><MessageSquare/>Trợ lý theo ngữ cảnh</span><button onClick={()=>setChatOpen(false)}>×</button></div><div className="chat-log">{messages.length===0&&<p>Hãy hỏi về kết quả đang xem.</p>}{messages.map((m,i)=><div key={i} className={m.role}>{m.text}</div>)}</div></>}</div>
    <footer className="chatbar"><button className="chat-shield" onClick={()=>setChatOpen(v=>!v)}><Shield/></button><input value={question} onFocus={()=>setChatOpen(true)} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={view==='email'?'Hỏi về email này...':'Hỏi về kết quả đánh giá này...'}/><span className="context">Ngữ cảnh: {view==='email'?'Email Guard':'Website Check'}</span><button className="send" onClick={send}><Send/>Gửi</button></footer>
    <div className="statusbar"><span><Wifi/>Backend: localhost:8000</span><span>Browser Cover • Nội dung nguy hiểm không được render</span><span>Electron {window.desktop?.version||'desktop'}</span></div>
  </main>;
}
function EmptyWeb({setUrl,scan}:{setUrl:(x:string)=>void;scan:()=>void}){return <div className="empty"><div className="orb"><Shield size={58}/><i/><i/><i/></div><span className="eyebrow">BROWSER COVER</span><h1>Kiểm tra trước.<br/><em>Duyệt web an toàn.</em></h1><p>Chúng tôi phân tích website thay bạn. Nội dung nguy hiểm không bao giờ được tải hoặc hiển thị trong ứng dụng.</p><div className="recent"><span>Thử nhanh</span>{['https://vietc0mbank-secure.xyz/login','https://github.com','https://bit.ly/x'].map((x,i)=><button key={x} onClick={()=>{setUrl(x);setTimeout(scan,10)}}><i className={i===1?'safe':i===2?'warn':'danger'}/>{x.replace('https://','')}</button>)}</div><div className="trust"><span><ShieldCheck/>Không render website</span><span><Check/>Giải thích bằng chứng</span><span><Globe2/>Kiểm tra URL + AI</span></div></div>}
function Pipeline({current,compact}:{current:string;compact?:boolean}){const steps=['Phân tích cấu trúc URL','Chạy model phân loại','Kiểm tra nội dung & prompt injection','Sinh giải thích & khuyến nghị'];const index=Math.max(0,steps.indexOf(current));return <div className={`pipeline ${compact?'compact':''}`}><div className="scanner"><Shield/><span/></div><span className="eyebrow">SECURE ANALYSIS PIPELINE</span><h2>{current}</h2><p>Website/email không được mở trên máy của bạn.</p><div className="steps">{steps.map((x,i)=><div className={i<index?'done':i===index?'running':''} key={x}><span>{i<index?<Check/>:i===index?<RefreshCw className="spin"/>:i+1}</span><b>{x}</b><small>{i<index?'Hoàn tất':i===index?'Đang xử lý...':'Đang chờ'}</small></div>)}</div></div>}
function ResultPanel({result,target,exportReport}:{result:Assessment;target:string;exportReport:()=>void}){return <div className="result"><div className="result-head"><div><span className="eyebrow">KẾT QUẢ PHÂN TÍCH</span><h2>{target}</h2><small>Mã yêu cầu: {result.requestId}</small></div><div className={`verdict ${result.riskLevel}`}><b>{result.score}</b><span>/100<br/>{riskText(result)}</span></div></div><div className="result-grid"><div className="score-card"><RiskRing result={result}/><p>Độ tin cậy <b>{Math.round(result.confidence*100)}%</b></p><small>Điểm số không thay thế đánh giá của con người.</small></div><div className="evidence"><h3><Search/>Bằng chứng phân tích</h3>{result.evidence.map((e,i)=><div className="evidence-row" key={i}><span>{i+1}</span><div><b>{e.feature||e.source}</b><p>{e.message}</p><meter min="-0.5" max="0.5" value={e.contribution||0}/></div><strong>{e.contribution!=null?`${e.contribution>0?'+':''}${e.contribution.toFixed(2)}`:''}</strong></div>)}</div></div><div className={`explanation ${result.riskLevel}`}><AlertTriangle/><div><b>Giải thích & khuyến nghị</b><p>{result.explanation||result.reasons.join('. ')}</p></div></div><div className="actions"><button className="danger-btn"><Ban/>Chặn domain này</button><button onClick={exportReport}><Download/>Xuất báo cáo</button><button><HelpCircle/>Báo sai</button><span>{result.latencyMs||0} ms • AI hỗ trợ quyết định</span></div></div>}
function RiskRing({result}:{result:Assessment}){return <div className={`risk-ring ${result.riskLevel}`} style={{'--score':`${result.score*3.6}deg`} as React.CSSProperties}><div><Shield/><b>{result.score}</b><span>/100</span><strong>{riskText(result)}</strong></div></div>}
function MailResult({mail,onScan,exportReport}:{mail:MailItem;onScan:()=>void;exportReport:()=>void}){if(!mail.result)return <div className="mail-empty"><Mail/><h2>{mail.subject}</h2><p>Email đang được cô lập. Nhấn đánh giá để xem tín hiệu mà không render nội dung gốc.</p><button className="scan" onClick={onScan}>Đánh giá email</button></div>;const r=mail.result;return <><div className="mail-meta"><span>Từ</span><b>{mail.sender} &lt;{mail.email}&gt;</b><span>Chủ đề</span><b>{mail.subject}</b></div><div className={`mail-verdict ${r.riskLevel}`}><RiskRing result={r}/><div><span className="eyebrow">ĐÁNH GIÁ THƯ ĐANG CHỌN</span><h2>{riskText(r)}</h2><p>Độ tin cậy {Math.round(r.confidence*100)}%</p></div></div><h3 className="why">Vì sao bị chấm điểm này</h3><div className="reason-list">{r.reasons.map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p></div>)}</div><div className="explanation"><Shield/><p>{r.explanation}</p></div><div className="actions"><button className="danger-btn"><Ban/>Chặn người gửi</button><button onClick={exportReport}><Download/>Xuất báo cáo</button><button><AlertTriangle/>Báo sai</button></div><button className="reveal"><HelpCircle/>Tôi hiểu rủi ro — xem thư gốc đã khử liên kết</button></>}
function LocalShield(){
  const [report,setReport]=useState<LocalFileReport|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [sandbox,setSandbox]=useState<{available:boolean;reason:string}|null>(null);
  async function choose(){if(!window.desktop)return setMessage('Chức năng này chỉ hoạt động trong ứng dụng Electron.');setBusy(true);setMessage('Đang đọc metadata, SHA-256 và chữ ký số...');try{const r=await window.desktop.localSecurity.chooseExecutable();if(r){setReport(r);setMessage('Đã kiểm tra tĩnh. Tệp chưa được thực thi.')}else setMessage('Đã hủy chọn tệp.');}catch(e){setMessage(e instanceof Error?e.message:'Không thể kiểm tra tệp.')}finally{setBusy(false)}}
  async function checkSandbox(){if(!window.desktop)return;const s=await window.desktop.localSecurity.sandboxStatus();setSandbox(s);setMessage(s.reason)}
  async function quarantine(){if(!report||!window.desktop)return;try{const r=await window.desktop.localSecurity.quarantine(report.path);setMessage(`${r.note} Vị trí: ${r.path}`)}catch(e){setMessage(e instanceof Error?e.message:'Cô lập thất bại.')}}
  async function openSandbox(){if(!report||!window.desktop)return;try{const r=await window.desktop.localSecurity.openSandbox(report.path);setMessage(r.note)}catch(e){setMessage(e instanceof Error?e.message:'Không mở được môi trường ảo.')}}
  return <section className="local-shield"><div className="local-hero"><div><span className="eyebrow">LOCAL SECURITY • WINDOWS</span><h1>Bảo vệ tệp ngay trên máy</h1><p>Kiểm tra tĩnh tệp thực thi, đưa bản sao vào kho cô lập và mở Windows Sandbox với mạng bị tắt. AI Security Armor không tự chạy tệp lạ trên hệ điều hành thật.</p></div><div className="local-state"><ShieldCheck/><b>Local Shield</b><span>Đang bảo vệ</span></div></div><div className="local-grid"><article className="local-card primary-card"><FileSearch/><span className="eyebrow">STATIC INSPECTION</span><h2>Kiểm tra EXE lạ</h2><p>Đọc SHA-256, kích thước và chữ ký Authenticode mà không thực thi tệp.</p><button className="scan" onClick={choose} disabled={busy}>{busy?<RefreshCw className="spin"/>:<FileUp/>}{busy?'Đang kiểm tra':'Chọn tệp EXE/MSI'}</button></article><article className="local-card"><PackageOpen/><span className="eyebrow">QUARANTINE VAULT</span><h2>Kho cô lập</h2><p>Tạo bản sao đổi đuôi <code>.quarantine</code> trong vùng dữ liệu riêng của ứng dụng, đặt chỉ đọc.</p><button disabled={!report} onClick={quarantine}><LockKeyhole/>Cô lập bản sao</button></article><article className="local-card"><Box/><span className="eyebrow">VIRTUAL ENVIRONMENT</span><h2>Windows Sandbox</h2><p>Môi trường dùng một lần, tắt mạng/clipboard/máy in và chỉ gắn thư mục mẫu ở chế độ chỉ đọc.</p><button onClick={checkSandbox}><RefreshCw/>Kiểm tra hỗ trợ</button><button className="sandbox-btn" disabled={!report||sandbox?.available===false} onClick={openSandbox}><Box/>Mở môi trường ảo</button></article></div>{message&&<div className="local-message"><Shield/>{message}</div>}{report&&<div className="file-report"><div className="file-report-head"><div><span className="eyebrow">FILE ASSESSMENT</span><h2>{report.name}</h2><small>{report.path}</small></div><span className={`signature ${report.risk}`}>{report.signatureStatus==='Valid'?<Check/>:<AlertTriangle/>}{report.signatureStatus==='Valid'?'CHỮ KÝ HỢP LỆ':'CHƯA TIN CẬY'}</span></div><div className="file-facts"><div><small>SHA-256</small><code>{report.sha256}</code></div><div><small>Kích thước</small><b>{(report.size/1024/1024).toFixed(2)} MB</b></div><div><small>Nhà phát hành</small><b>{report.signer||'Không xác định'}</b></div><div><small>Cập nhật</small><b>{new Date(report.modifiedAt).toLocaleString('vi-VN')}</b></div></div><h3>Tín hiệu an toàn</h3>{report.reasons.map((x,i)=><div className="local-reason" key={x}><span>{i+1}</span>{x}</div>)}<div className="local-warning"><AlertTriangle/><p><b>Không phải antivirus hoàn chỉnh.</b> Chức năng hiện tại kiểm tra tĩnh và tận dụng Windows Sandbox. Không tự chạy mẫu, không thay thế Microsoft Defender/EDR và không đảm bảo tệp an toàn tuyệt đối.</p></div></div>}</section>
}
function SettingsView(){const [threshold,setThreshold]=useState(70);return <section className="settings-view"><aside><h2>Cài đặt</h2>{['Chung','Bảo vệ','Email','Tài khoản'].map((x,i)=><button className={i===0?'active':''} key={x}>{i===0?<Settings/>:i===1?<Shield/>:i===2?<Mail/>:<CircleUserRound/>}{x}</button>)}</aside><article><span className="eyebrow">PREFERENCES</span><h1>Thiết lập ứng dụng</h1><div className="setting-group"><h3>Chung</h3><label><span><b>Ngôn ngữ</b><small>Ngôn ngữ giao diện và giải thích</small></span><select><option>Tiếng Việt</option><option>English</option></select></label><label><span><b>Giao diện</b><small>Chủ đề hiển thị</small></span><div className="segmented"><button>Sáng</button><button className="active">Tối</button><button>Hệ thống</button></div></label></div><div className="setting-group"><h3>Bảo vệ</h3><label><span><b>Ngưỡng cảnh báo</b><small>Hiển thị cảnh báo khi điểm vượt ngưỡng</small></span><div className="range"><input type="range" min="40" max="90" value={threshold} onChange={e=>setThreshold(+e.target.value)}/><b>{threshold}/100</b></div></label><Toggle title="Tự chặn rủi ro cao" note="Tự động chặn khi điểm từ 80 trở lên"/><Toggle title="Quét prompt injection" note="Phát hiện chỉ dẫn ẩn nhắm vào AI agent"/></div><div className="setting-group"><h3>Quyền riêng tư</h3><Toggle title="Lưu lịch sử cục bộ" note="Dữ liệu chỉ lưu trên thiết bị này"/><button className="outline-danger">Xóa toàn bộ lịch sử</button></div></article></section>}
function Toggle({title,note}:{title:string;note:string}){const [on,setOn]=useState(true);return <label><span><b>{title}</b><small>{note}</small></span><button onClick={()=>setOn(!on)} className={`toggle ${on?'on':''}`}><i/></button></label>}
export default App;
